### ISSUE TITLE
JIT fails to request memory on WSL2 Ubuntu 20.04

### ISSUE THREAD

**Issue by froyo-np** [dzaima/CBQN#99]
On WSL2, Ubuntu 20.04, x86/64 architecture, `free -h` showing 19Gi available.
`git clone https://github.com/dzaima/CBQN.git`
`cd CBQN`
`make`
it seems to get pretty far - in the output, I see "Using precompiled bytecode..."
it ends with "load.c" followed by the error:
CBQN encountered a fatal error: Failed to allocate memory for JIT 200 times; stopping trying
automatically-built bootstrap CBQN doesn't behave as expected; run 'make for-build' with necessary configuration manually

I would be happy to make for-build manually, but I'm having trouble figuring out what configuration to use. Any help would be greatly appreciated!

**Comment by dzaima** [comment]
Huh. To avoid that error, you'd need `make for-build f=-DJIT_ENABLED=0`, and then `make f=-DJIT_ENABLED=0` for the primary build too.

What's `cc --version` and `echo '#include <sys/mman.h>' | cc -E -dM - | grep MAP_FIXED` for you?

**Comment by dzaima** [comment]
Also `uname -rv`

**Comment by froyo-np** [comment]
its alive! Thanks!!

requested info:
cc version:
cc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
sys/mman.h:
#define MAP_FIXED_NOREPLACE 0x100000
#define MAP_FIXED 0x10
uname -rv:
4.4.0-19041-Microsoft #3636-Microsoft Thu Oct 19 17:41:00 PST 2023

**Comment by dzaima** [comment]
So linux kernel 4.4.0 is before 4.17 which adds `MAP_FIXED_NOREPLACE` support, making it a no-op. That's not _bad_ by itself, but presumably the address hint is ignored enough to make that not work either. Not sure what I can really do here, besides just adding an `if (kernel version < 4.17) disable_jit();`.

Though, actually, perhaps with the `for-build` built, a plain `make` (i.e. without `f=-DJIT_ENABLED=0`) might work?

(on x86-64 the final build, unlike the bootstrap one, should have position-independentness disabled, at which point the `MAP_32BIT` flag should make the JIT allocations work)

**Comment by froyo-np** [comment]
1. `make o3n` works on its own after the DJIT_ENABLED=0 for-build step.
2. I'm really not well versed in linux stuff - if this is a "keep your kernel up to date" sort of thing, my apologies!

**Comment by dzaima** [comment]
Ideally CBQN would work on all kernels that are in active use (I test on my android phone which has an even older kernel of 3.18, but it's ARM so the JIT isn't used as it's x86_64-only). The JIT allocation thing has caused issues before too (even hit a kernel bug).

The problem is that JIT code must be at most 2^31 bytes away from the main code so that it can call functions in it by a 32-bit immediate, but there's no way to request memory in a specific range (`MAP_FIXED_NOREPLACE` allows choosing a specific address at least). QEMU does this by getting JIT memory as a 100MB-or-whatever zeroed data section, perhaps it'd be worth looking into doing something similar (this does mean a hard upper limit on JIT code size, though there already is one with the 2^31 limit).

**Comment by m2608** [comment]
I had the same problem compiling cbqn for FreeBSD. Your fix with `f=-DJIT_ENABLED=0` worked, thank you!

```
~# uname -rv
14.0-RELEASE-p3 FreeBSD 14.0-RELEASE-p3 #0: Mon Dec 11 04:56:01 UTC 2023     root@amd64-builder.daemonology.net:/usr/obj/usr/src/amd64.amd64/sys/GENERIC

~# cc --version
FreeBSD clang version 16.0.6 (https://github.com/llvm/llvm-project.git llvmorg-16.0.6-0-g7cbf1a259152)
Target: x86_64-unknown-freebsd14.0
Thread model: posix
InstalledDir: /usr/bin

~# echo '#include <sys/mman.h>' | cc -E -dM - | grep MAP_FIXED
#define MAP_FIXED 0x0010
```

**Comment by dzaima** [comment]
@m2608 does it work with this applied? (run `make clean` beforehand, otherwise the bootstrap build won't rerun)

```diff
diff --git a/src/jit/nvm_x86_64.c b/src/jit/nvm_x86_64.c
index a6e61f37..b82cec1a 100644
--- a/src/jit/nvm_x86_64.c
+++ b/src/jit/nvm_x86_64.c
@@ -49,6 +49,8 @@ static void* mmap_nvm(u64 sz) {
     int noreplace = 0;
     #ifdef MAP_FIXED_NOREPLACE
       noreplace|= MAP_FIXED_NOREPLACE;
+    #elif __FreeBSD__
+      noreplace|= MAP_FIXED|MAP_EXCL;
     #endif
     void* c = mmap((void*)loc, sz, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_NORESERVE|MAP_PRIVATE|MAP_ANONYMOUS|noreplace, -1, 0);
     if (c==MAP_FAILED) continue;
```

**Comment by m2608** [comment]
Yeah, it works with v0.4.0, but on master branch I got another error:

```
In file included from src/builtins/sysfn.c:11:
/usr/include/unistd.h:551:7: error: redefinition of 're_comp' as different kind of symbol
char    *re_comp(const char *);
         ^
src/builtins/../load.h:13:3: note: previous definition is here
  re_comp, re_compOpts, re_rt, re_glyphs, re_sysNames, re_sysVals, // compiling info
  ^
1 error generated.
```
It seems like renaming `re_comp` in `src/load.h` and `src/load.c` files does the trick.

Thanks for your help!

**Comment by dzaima** [comment]
...huh. yay for lack of namespacing in C I guess. `MAP_EXCL` & `re_comp` fixes are now on branch `develop`.

No changes for the linux<4.19 issue though, so this is remaining open. still not sure how I want to handle this. perhaps it'd make sense to just require existence of `MAP_FIXED_NOREPLACE` for JIT on linux? A bit sad as it can still work if the `MAP_32BIT` path can be utilized, but whatever, the existing JIT isn't that much of an improvement (only like max 2x for scalar code best-case)

**Comment by dzaima** [comment]
Pushed to `develop` disabling the JIT when targeting linux and `MAP_FIXED_NOREPLACE` isn't defined. (can still be manually enabled with a make arg of `f=-DJIT_ENABLED=1`)
